=== AlessandroZingali/Pixel-hub/Sorgente/XML/XML_Schema/Giochi_XML_schema.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" > 

  <xsd:element name="TabellaGiochi" > 
    <xsd:complexType> 
      <xsd:sequence> 
        <xsd:element ref="Gioco" minOccurs="0" maxOccurs="unbounded"/> 
      </xsd:sequence> 
    </xsd:complexType> 
  </xsd:element> 
   
 
  <xsd:element name="Gioco"> 
    <xsd:complexType> 
      <xsd:sequence>
        <xsd:element  ref="Titolo"  minOccurs="1"  maxOccurs="1" />
        <xsd:element  ref="Prezzo"  minOccurs="1"  maxOccurs="1" /> 
        <xsd:element  ref="CasaSviluppo"  minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element  ref="Publisher" minOccurs="1" maxOccurs="1" /> 
        <xsd:element ref="Descrizione" minOccurs="1" maxOccurs="1"/>
        <xsd:element  ref="RequisitiMinimi"   minOccurs="1" maxOccurs="1"/> 
        <xsd:element  ref="RequisitiRaccomandati" minOccurs="1" maxOccurs="1"/> 
        <xsd:element  ref="DataDiUscita"  minOccurs="1" maxOccurs="1"/> 
        <xsd:element  ref="Immagine"  minOccurs="1" maxOccurs="3"/>  
        <xsd:element  ref="Generi"   minOccurs="1" maxOccurs="unbounded"/> 
        <xsd:element  ref="Disponibile"   minOccurs="1" maxOccurs="1"/>
        <xsd:element  ref="MediaRecensioniAdmin"  minOccurs="1" maxOccurs="1"/> 
        <xsd:element  ref="MediaRecensioniUtenti" minOccurs="1" maxOccurs="1"/>
        <xsd:element  ref="TitoliCorrelati" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence> 
        <xsd:attribute name="id_gioco" type="xsd:integer" use="required"/> 
    </xsd:complexType> 
  </xsd:element>

  <xsd:element  name="Titolo"  type="xsd:string" />
  <xsd:element  name="Prezzo"  type="xsd:float" />
  <xsd:element  name="CasaSviluppo"  type="xsd:string" />
  <xsd:element  name="Publisher" type="xsd:string" />  
  <xsd:element  name="Descrizione" type="xsd:string" />
  <xsd:element  name="RequisitiMinimi"  type="xsd:string" /> 
  <xsd:element  name="RequisitiRaccomandati"  type="xsd:string"/> 
  <xsd:element  name="DataDiUscita" type="xsd:string"/> 
  <xsd:element  name="Immagine"  type="xsd:string"/> 
  <xsd:element  name="Generi"  type="xsd:string" /> 
  <xsd:element  name="Disponibile"  type="xsd:integer" /> 
  <xsd:element  name="MediaRecensioniAdmin"  type="xsd:float"/> 
  <xsd:element  name="MediaRecensioniUtenti"  type="xsd:float" />

  <xsd:element name="TitoliCorrelati" > 
  <xsd:complexType> 
      <xsd:sequence> 
        <xsd:element ref="idGiocoCorrelato"  minOccurs="1"  maxOccurs="unbounded"/> 
      </xsd:sequence> 
    </xsd:complexType> 
  </xsd:element>

  <xsd:element name="idGiocoCorrelato" type="xsd:integer" />
   
</xsd:schema>

=== AlessandroZingali/Pixel-hub/Sorgente/XML/Giochi.xml
<?xml version="1.0" encoding="UTF-8"?>
<TabellaGiochi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XML_Schema/Giochi_XML_schema.xsd">
  <Gioco id_gioco="1">
    <Titolo>Overwatch: Origin Edition</Titolo>
    <Prezzo>39.99</Prezzo>
    <CasaSviluppo>Blizzard Ent.</CasaSviluppo>
    <RequisitiMinimi>OS: Windows 7/8/10 64-bit; Processor: Intel Core i3 or AMD Phenom X3 8650; Memory: 4 GB RAM; Graphics: NVIDIA GeForce GTX 460, ATI Radeon HD 4850, or Intel HD Graphics 4400; DirectX: Version 11; Network: Broadband internet connection; Storage: 30 GB available space; Sound Card: DirectX Compatible</RequisitiMinimi>
    <RequisitiRaccomandati>OS: Windows 10 64-bit; Processor: Intel Core i5 or AMD Phenom II X3, 2.8 GHz; Memory: 6 GB RAM; Graphics: NVIDIA GeForce GTX 660 or AMD Radeon HD 7950; DirectX: Version 11; Network: Broadband internet connection; Storage: 30 GB available space; Sound Card: DirectX Compatible</RequisitiRaccomandati>
    <DataDiUscita>2016</DataDiUscita>
    <Immagine>ImmaginiGiochi/overwatch_logo.png</Immagine>  
    <Generi>Sparatutto</Generi>
    <Disponibile>1</Disponibile>   
    <MediaRecensioniAdmin>78.5</MediaRecensioniAdmin> 
    <MediaRecensioniUtenti>88.3</MediaRecensioniUtenti> 
    <TitoliCorrelati>
      <idGiocoCorrelato>5</idGiocoCorrelato>
      <idGiocoCorrelato>11</idGiocoCorrelato>
    </TitoliCorrelati>  
  </Gioco>
  <Gioco id_gioco="2">
    <Titolo>The Witcher 3: Wild Hunt</Titolo>
    <Prezzo>49.99</Prezzo>
    <CasaSviluppo>CD Projekt Red</CasaSviluppo>
    <RequisitiMinimi>OS: 64-bit Windows 7, 8.1, or 10; Processor: Intel CPU Core i5-2500K 3.3GHz / AMD CPU Phenom II X4 940; Memory: 6 GB RAM; Graphics: NVIDIA GPU GeForce GTX 660 / AMD GPU Radeon HD 7870; DirectX: Version 11; Network: Broadband internet connection; Storage: 35 GB available space; Sound Card: DirectX Compatible</RequisitiMinimi>
    <RequisitiRaccomandati>OS: 64-bit Windows 7, 8.1, or 10; Processor: Intel CPU Core i7 3770 3.4 GHz / AMD CPU AMD FX-8350 4 GHz; Memory: 8 GB RAM; Graphics: NVIDIA GPU GeForce GTX 770 / AMD GPU Radeon R9 290; DirectX: Version 11; Network: Broadband internet connection; Storage: 35 GB available space; Sound Card: DirectX Compatible</RequisitiRaccomandati>
    <DataDiUscita>2015</DataDiUscita>
    <Immagine>ImmaginiGiochi/witcher3_logo.png</Immagine>
    <Generi>RPG</Generi>
    <Disponibile>1</Disponibile>
    <MediaRecensioniAdmin>93.0</MediaRecensioniAdmin>
    <MediaRecensioniUtenti>81.5</MediaRecensioniUtenti>
    <TitoliCorrelati>
      <idGiocoCorrelato>8</idGiocoCorrelato>
      <idGiocoCorrelato>14</idGiocoCorrelato>
    </TitoliCorrelati>
  </Gioco>
  <Gioco id_gioco="3">
    <Titolo>Cyberpunk 2077</Titolo>
    <Prezzo>59.99</Prezzo>
    <CasaSviluppo>CD Projekt Red</CasaSviluppo>
    <RequisitiMinimi>OS: Windows 10 64-bit; Processor: Intel Core i5-3570K or AMD FX-8310; Memory: 8 GB RAM; Graphics: NVIDIA GeForce GTX 780 or AMD Radeon RX 470; DirectX: Version 12; Network: Broadband internet connection; Storage: 70 GB available space; Sound Card: DirectX Compatible</RequisitiMinimi>
    <RequisitiRaccomandati>OS: Windows 10 64-bit; Processor: Intel Core i7-4790 or AMD Ryzen 3 3200G; Memory: 12 GB RAM; Graphics: NVIDIA GeForce GTX 1060 or AMD Radeon R9 Fury; DirectX: Version 12; Network: Broadband internet connection; Storage: 70 GB available space; Sound Card: DirectX Compatible</RequisitiRaccomandati>
    <DataDiUscita>2020</DataDiUscita>
    <Immagine>ImmaginiGiochi/cyberpunk2077_logo.png</Immagine>
    <Generi>RPG</Generi>
    <Disponibile>1</Disponibile>
    <MediaRecensioniAdmin>78.0</MediaRecensioniAdmin>
    <MediaRecensioniUtenti>90</MediaRecensioniUtenti>
    <TitoliCorrelati>
      <idGiocoCorrelato>2</idGiocoCorrelato>
      <idGiocoCorrelato>9</idGiocoCorrelato>
    </TitoliCorrelati>
  </Gioco>
</TabellaGiochi>
