=== AlessandroZingali/Pixel-hub/Sorgente/XML/XML_Schema/Log_Transazioni_Giochi_XML_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    <xsd:element name="LogTransazioniGiochi">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Transazione" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="Transazione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Gioco" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="IDTransazione" type="xsd:integer" use="required"/>
            <xsd:attribute name="IDGiocatore" type="xsd:integer"/>
            <xsd:attribute name="ModCommentiUsato" type="xsd:float" use="required"/>
            <xsd:attribute name="DataOra" type="xsd:dateTime" use="required"/>
            <xsd:attribute name="PixelIniziali" type="xsd:integer" use="required"/>
        </xsd:complexType>
        </xsd:element>
        <xsd:element name="Gioco">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element ref="Titolo" minOccurs="1" maxOccurs="1"/>
                    <xsd:element ref="IDGioco" minOccurs="1" maxOccurs="1"/>
                    <xsd:element ref="Importo" minOccurs="1" maxOccurs="1"/> 
                </xsd:sequence>
            </xsd:complexType>
    </xsd:element>
    <xsd:element name="Titolo" type="xsd:string"/>
    <xsd:element name="IDGioco" type="xsd:integer"/>
    <xsd:element name="Importo" type="xsd:float"/>
</xsd:schema>

=== AlessandroZingali/Pixel-hub/Sorgente/XML/LogTransazioniGiochi.xml
<?xml version="1.0" encoding="UTF-8"?>
<LogTransazioniGiochi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XML_Schema/Log_Transazioni_Giochi_XML_Schema.xsd">
  <Transazione IDTransazione="2" ModCommentiUsato="0.01" IDGiocatore="1" DataOra="02/02/26 16:33" PixelIniziali="199">
    <Gioco>
      <Titolo>Clair Obscur:Expedition 33</Titolo>
      <IDGioco>5</IDGioco>
      <Importo>14.99</Importo>
    </Gioco>
  </Transazione>
  <Transazione IDTransazione="3" ModCommentiUsato="0.01" IDGiocatore="1" DataOra="02/02/26 16:35" PixelIniziali="273">
    <Gioco>
      <Titolo>Clair Obscur:Expedition 33</Titolo>
      <IDGioco>5</IDGioco>
      <Importo>14.99</Importo>
    </Gioco>
  </Transazione>
  <Transazione IDTransazione="4" ModCommentiUsato="0.01" IDGiocatore="1" DataOra="02/02/26 16:37" PixelIniziali="347">
    <Gioco>
      <Titolo>Clair Obscur:Expedition 33</Titolo>
      <IDGioco>5</IDGioco>
      <Importo>14.99</Importo>
    </Gioco>
  </Transazione>
  <Transazione IDTransazione="5" ModCommentiUsato="0.01" IDGiocatore="1" DataOra="02/02/26 16:37" PixelIniziali="421">
    <Gioco>
      <Titolo>Borderlands</Titolo>
      <IDGioco>9</IDGioco>
      <Importo>59.99</Importo>
    </Gioco>
  </Transazione>
  <Transazione IDTransazione="6" ModCommentiUsato="0.01" IDGiocatore="1" DataOra="02/02/26 16:39" PixelIniziali="720">
    <Gioco>
      <Titolo>Doom Eternal</Titolo>
      <IDGioco>10</IDGioco>
      <Importo>49.99</Importo>
    </Gioco>
  </Transazione>
  <Transazione IDTransazione="7" ModCommentiUsato="0.01" IDGiocatore="1" DataOra="02/02/26 16:40" PixelIniziali="969">
    <Gioco>
      <Titolo>Helldivers II</Titolo>
      <IDGioco>6</IDGioco>
      <Importo>39.99</Importo>
    </Gioco>
  </Transazione>
  <Transazione IDTransazione="7" ModCommentiUsato="1" IDGiocatore="4" DataOra="11/02/26 13:00" PixelIniziali="500">
    <Gioco>
      <Titolo>Borderlands</Titolo>
      <IDGioco>9</IDGioco>
      <Importo>59.99</Importo>
    </Gioco>
  </Transazione>
  <Transazione IDTransazione="8" ModCommentiUsato="1.2083333333333" IDGiocatore="4" DataOra="11/02/26 13:03" PixelIniziali="799">
    <Gioco>
      <Titolo>Civilization VI</Titolo>
      <IDGioco>22</IDGioco>
      <Importo>29.99</Importo>
    </Gioco>
  </Transazione>
  <Transazione IDTransazione="9" ModCommentiUsato="0.79" IDGiocatore="4" DataOra="11/02/26 13:08" PixelIniziali="948">
    <Gioco>
      <Titolo>Cyberpunk 2077</Titolo>
      <IDGioco>3</IDGioco>
      <Importo>53.99</Importo>
    </Gioco>
  </Transazione>
  <Transazione IDTransazione="10" ModCommentiUsato="1.08" IDGiocatore="4" DataOra="11/02/26 13:11" PixelIniziali="1217">
    <Gioco>
      <Titolo>The Witcher 3: Wild Hunt</Titolo>
      <IDGioco>2</IDGioco>
      <Importo>47.49</Importo>
    </Gioco>
  </Transazione>
</LogTransazioniGiochi>
