=== AlessandroZingali/Pixel-hub/Sorgente/XML/XML_Schema/Profile_Pic_XML_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="listaPic">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Pic" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Pic">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nome" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="prezzo" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="path" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
            <xsd:attribute name="id_pic" type="xsd:integer" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="nome" type="xsd:string"/>
    <xsd:element name="prezzo" type="xsd:integer"/>
    <xsd:element name="path" type="xsd:string"/>

</xsd:schema>

=== AlessandroZingali/Pixel-hub/Sorgente/XML/ProfilePIc.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaPic xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XML_Schema/Profile_Pic_XML_Schema.xsd">
    <Pic id_pic="1">
        <nome>Shadow</nome>
        <prezzo>100</prezzo>
        <path>ProfilePic/Shadow.png</path>
    </Pic>
    <Pic id_pic="2">
        <nome>SpiderMan</nome>
        <prezzo>120</prezzo>
        <path>ProfilePic/Spiderman.png</path>
    </Pic>
    <Pic id_pic="3">
        <nome>SpongeBob Matrix</nome>
        <prezzo>120</prezzo>
        <path>ProfilePic/SpongebobMatrix.png</path>
    </Pic>
    <Pic id_pic="4">
        <nome>Sorcer Yoshi</nome>
        <prezzo>200</prezzo>
        <path>ProfilePic/Yoshi.png</path>
    </Pic>

</listaPic>
