=== AlessandroZingali/Pixel-hub/Sorgente/XML/XML_Schema/Sconti_XML_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >

  <xsd:element name="listaSconti">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Sconto" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Sconto">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element  ref="Gioco" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
        <xsd:attribute name="id_tipoSconto" type="xsd:integer" use="required"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="Gioco">
    <xsd:complexType>
      <xsd:simpleContent>
      <xsd:extension base="xsd:integer">
       <xsd:attribute name="valoreSconto" type="xsd:integer" use="required"/>
       </xsd:extension>
       </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="id_gioco" type="xsd:integer" />

</xsd:schema>

=== AlessandroZingali/Pixel-hub/Sorgente/XML/Sconti.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaSconti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XML_Schema/Sconti_XML_schema.xsd">
  <Sconto id_tipoSconto="1">
    <Gioco valoreSconto="20">8</Gioco>
    <Gioco valoreSconto="20">5</Gioco>
    <Gioco valoreSconto="10">6</Gioco>
    <Gioco valoreSconto="15">1</Gioco>
    <Gioco valoreSconto="10">23</Gioco>
    <Gioco valoreSconto="10">15</Gioco>
    <Gioco valoreSconto="10">14</Gioco>
  </Sconto>
  <Sconto id_tipoSconto="2">
    <Gioco valoreSconto="15">8</Gioco>
    <Gioco valoreSconto="20">1</Gioco>
    <Gioco valoreSconto="20">16</Gioco>
    <Gioco valoreSconto="10">12</Gioco>
    <Gioco valoreSconto="10">11</Gioco>
    <Gioco valoreSconto="10">18</Gioco>
    <Gioco valoreSconto="15">4</Gioco>
    <Gioco valoreSconto="5">23</Gioco>
    <Gioco valoreSconto="5">15</Gioco>
  </Sconto>
  <Sconto id_tipoSconto="3">
    <Gioco valoreSconto="5">17</Gioco>
    <Gioco valoreSconto="3">13</Gioco>
    <Gioco valoreSconto="10">3</Gioco>
    <Gioco valoreSconto="5">5</Gioco>
    <Gioco valoreSconto="5">21</Gioco>
    <Gioco valoreSconto="5">25</Gioco>
  </Sconto>
  <Sconto id_tipoSconto="4"/>
  <Sconto id_tipoSconto="5">
    <Gioco valoreSconto="5">9</Gioco>
    <Gioco valoreSconto="10">20</Gioco>
    <Gioco valoreSconto="10">2</Gioco>
    <Gioco valoreSconto="5">19</Gioco>
    <Gioco valoreSconto="3">17</Gioco>
    <Gioco valoreSconto="10">14</Gioco>
    <Gioco valoreSconto="20">23</Gioco>
  </Sconto>
  <Sconto id_tipoSconto="6">
    <Gioco valoreSconto="20">22</Gioco>
    <Gioco valoreSconto="10">16</Gioco>
  </Sconto>
  <Sconto id_tipoSconto="7"/>
  <Sconto id_tipoSconto="8">
    <Gioco valoreSconto="15">8</Gioco>
    <Gioco valoreSconto="5">25</Gioco>
  </Sconto>
  <Sconto id_tipoSconto="9">
    <Gioco valoreSconto="15">23</Gioco>
    <Gioco valoreSconto="5">20</Gioco>
    <Gioco valoreSconto="5">2</Gioco>
    <Gioco valoreSconto="10">7</Gioco>
    <Gioco valoreSconto="10">17</Gioco>
    <Gioco valoreSconto="10">25</Gioco>
  </Sconto>
</listaSconti>
