=== AlessandroZingali/Pixel-hub/Sorgente/XML/XML_Schema/SettingsSconti_XML_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="Settings">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="MinimiSpesi" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="MinimiSpesiDa" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="listaGiochiAdmin" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="ReputazioneMin" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="MesiMin" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="AnniMin" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="CasaSconto" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="GenereSconto" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="GradoSconto" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="MinimiSpesi" type="xsd:float"/>
    <xsd:element name="ReputazioneMin" type="xsd:float"/>
    <xsd:element name="MesiMin" type="xsd:integer"/>
    <xsd:element name="AnniMin" type="xsd:integer"/>
    <xsd:element name="GenereSconto" type="xsd:string"/>
    <xsd:element name="CasaSconto" type="xsd:string"/>

    <xsd:element name="MinimiSpesiDa">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Valore" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="DataInizio" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="listaGiochiAdmin">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Gioco" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="Valore" type="xsd:float"/>
    <xsd:element name="DataInizio">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
            <xsd:pattern value="\d{2}-\d{2}-\d{4}"/>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <xsd:element name="Gioco" type="xsd:integer"/>

    <xsd:element name="GradoSconto">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="TipoSconto" minOccurs="3" maxOccurs="3"/>
            </xsd:sequence>
            <xsd:attribute name="Grado" type="xsd:integer" use="required"/>
            </xsd:complexType>
    </xsd:element>

    <xsd:element name="TipoSconto">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Sconto" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
            </xsd:complexType>
    </xsd:element>
    <xsd:element name="Sconto" type="xsd:float"/>

</xsd:schema>

=== AlessandroZingali/Pixel-hub/Sorgente/XML/SettingsSconti.xml
<?xml version="1.0" encoding="UTF-8"?>
<Settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XML_Schema/SettingsSconti_XML_Schema.xsd">
    <MinimiSpesi>100</MinimiSpesi>
    <MinimiSpesiDa>
        <Valore>1000</Valore>
        <DataInizio>05-05-2026</DataInizio>
    </MinimiSpesiDa>
    <ReputazioneMin>100</ReputazioneMin>
    <MesiMin>6</MesiMin>
    <AnniMin>1</AnniMin>
    <CasaSconto>From Software</CasaSconto>
    <GenereSconto>FPS</GenereSconto>
</Settings>
